# ----------------------------
#  Andrea Silvestroni 2019
#  Residual Noise Extraction and Smartphone Linking
#
# ----------------------------

from django.db import models

from . import Session


class PictureCluster(models.Model):
    """
    Model representing a cluster of Pictures on the system. It's generated by clustering pictures together through
    their residual noises
    """

    type = models.CharField(max_length=20)
    label = models.CharField(max_length=20)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    original = models.BooleanField(default=False)

    @property
    def pattern_noise_path(self):
        """
        :return: Path to the Pattern Noise of the Cluster (average of its Pictures residual noises)
        """
        return 'storage/{}/{}/cluster_{}_noise.npy'.format(self.session.id, self.type, self.label)

    def delete(self, using=None, keep_parents=False):
        """
        Override default delete method to also delete the cluster's pattern noise file
        """
        import os

        os.remove(self.pattern_noise_path)
        super().delete(using, keep_parents)
