# Generated by Django 2.1.7 on 2019-02-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='state',
            new_name='stage',
        ),
    ]
