# Generated by Django 2.1.7 on 2019-02-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190216_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
